name: deploy in apigee x

on:
  workflow_dispatch:

jobs:
  build:
    name: "Deploy To Apigee X"
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Instal node
        uses: actions/setup-node@v3
      - name: Install apigeelint
        run: npm install -g apigeelint
      - name: Analyse nos-oauth-prod-v3
        run: apigeelint -s apigee-github-actions/apiproxy -f table.js
      - id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: "${{secrets.WORKLOAD_IDENTITY_POOL_ID}}"
          service_account: "${{secrets.SERVICE_ACCOUNT}}"
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV
      - name: Deploy to Cloud Run
        run: |-
          gcloud --quiet beta apigee archives deploy --environment=test-arc --organization=apigeexnosi --labels=release=$NOW 
